###################### CONFIG ####################
BOT_NAME = "crawler"

SPIDER_MODULES = ["crawler.spiders"]
NEWSPIDER_MODULE = "crawler.spiders"

USER_AGENT = "crawler"

ROBOTSTXT_OBEY = False   # big speed improvement

# Performance
CONCURRENT_REQUESTS = 32
CONCURRENT_REQUESTS_PER_DOMAIN = 16
DOWNLOAD_DELAY = 0.25

REACTOR_THREADPOOL_MAXSIZE = 64

COOKIES_ENABLED = False
TELNETCONSOLE_ENABLED = False
LOG_LEVEL = "WARNING"

# Crawl limits
DEPTH_LIMIT = 50
CLOSESPIDER_PAGECOUNT = 500

# Network
DOWNLOAD_TIMEOUT = 10
RETRY_ENABLED = True
RETRY_TIMES = 1

COMPRESSION_ENABLED = True

FEED_EXPORT_ENCODING = "utf-8"

# Auto-throttle (prevents bans but keeps speed high)
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 0.25
AUTOTHROTTLE_MAX_DELAY = 5
AUTOTHROTTLE_TARGET_CONCURRENCY = 8