######################CONFIG####################
BOT_NAME = "crawler"

SPIDER_MODULES = ["crawler.spiders"]
NEWSPIDER_MODULE = "crawler.spiders"

USER_AGENT = "crawler"

ROBOTSTXT_OBEY = True

# Performance
CONCURRENT_REQUESTS = 2
CONCURRENT_REQUESTS_PER_DOMAIN = 1
DOWNLOAD_DELAY = 2

REACTOR_THREADPOOL_MAXSIZE = 32

COOKIES_ENABLED = False
TELNETCONSOLE_ENABLED = False
LOG_LEVEL = "WARNING"

# Crawl limits
DEPTH_LIMIT = 50
CLOSESPIDER_PAGECOUNT = 2000

# Network
DOWNLOAD_TIMEOUT = 15
RETRY_ENABLED = True
RETRY_TIMES = 2

COMPRESSION_ENABLED = True

FEED_EXPORT_ENCODING = "utf-8"